### ISSUE TITLE
"NoSuchElementException"

### ISSUE THREAD

**Issue by pedrocoutinhoo19** [felipesergiob/Filma#4]
"No Such element exception" Esse erro ocorreu no método login do caso de teste. Indica que o elemento designado como "password" não pôde ser localizado

**Comment by brunnapontual** [comment]
Resolução: 
        wait = WebDriverWait(driver, 10)
        time.sleep(2)

        favoritar = wait.until(EC.visibility_of_element_located((By.ID, "fav_unfilled")))
        driver.execute_script("arguments[0].scrollIntoView();", favoritar)
        time.sleep(1)

        actions = ActionChains(driver)
        actions.move_to_element(favoritar).perform()
        time.sleep(1)

        favoritar.click()
        time.sleep(2)

        Desfavoritar = wait.until(EC.visibility_of_element_located((By.ID, "fav_filled")))
        driver.execute_script("arguments[0].scrollIntoView();", Desfavoritar)
        time.sleep(1)

        actions = ActionChains(driver)
        actions.move_to_element(Desfavoritar).perform()
        time.sleep(1)

        Desfavoritar.click()
        time.sleep(2)
